version: '3.8'

services:
  
  postgres:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres:15.3
    restart: unless-stopped
    environment:
        DATABASE_HOST: ${DATABASE_HOST}
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_MAINTENANCE_DB}
    ports:
        - "5434:${DATABASE_CONTAINER_PORT}"
    volumes:
        - ${DATABASE_HOST_DATA}:${DATABASE_CONTAINER_DATA}
