version: '3.8'

services:
  internal_api:
    container_name: school_internal_api
    image: school/school_internal_api:dev
    restart: unless-stopped
    ports:
      - "5236:5236"
      - "7228:7228"
    
    environment:
      - ASPNETCORE_URLS=http://+:5236;http://+:7228;
      - ASPNETCORE_ENVIRONMENT=Development

    healthcheck:
      test: curl --fail http://localhost:7228/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
      start_interval: 10s

    build:
      context: ..
      dockerfile: InternalAPI\Dockerfile

    depends_on:
      postgres:
        condition: service_started

  public_api:
    container_name: school_public_api
    image: school/school_public_api:dev
    restart: unless-stopped
    ports:
      - "5166:5166"
    
    environment:
      - ASPNETCORE_URLS=http://+:5166;
      - ASPNETCORE_ENVIRONMENT=Development

    healthcheck:
      test: curl --fail http://localhost:5166/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
      start_interval: 10s

    build:
      context: ..
      dockerfile: PublicApi\Dockerfile

    depends_on:
      internal_api:
        condition: service_healthy
      postgres:
        condition: service_started

  postgres:
    container_name: school_postgres
    image: postgres:15.3
    restart: unless-stopped
    environment:
        DATABASE_HOST: 127.0.0.1
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: SummerSchoolDocker
    ports:
        - "5434:5432"
    volumes:
        - ./DockerData/postgres/data:/var/lib/postgresql/data
